### ISSUE TITLE
getSearch problem

### ISSUE THREAD

**Issue by siavashsoleymani** [BoyCook/TwitterJSClient#64]
twitter.getSearch({'q':'#haiku','count': 10}, error, success);
        ^

TypeError: twitter.getSearch is not a function
    at Object.<anonymous> (/home/siavash/Desktop/node js/twitterApi/index.js:21:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by FedericoAlvarez** [comment]
I have the same issue, How do you fix it? @siavashsoleymani
